/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package junk.frontend;

import java.util.ArrayList;
import junk.backend.Database;

/**
 *
 * @author kiedr
 */
public class Stats extends javax.swing.JFrame {

    Database db = new Database();
    ArrayList<String> expCar = new ArrayList<String>();
    ArrayList<String> cheapCar = new ArrayList<String>();
    String expCarPrice, cheapCarPrice, cheapCarData, expCarData;
    int summedPrice, maxTransactionValue;
    
    /**
     * Creates new form Stats
     */
    public Stats() {
        initComponents();
        ShowExpCar();
        ShowCheapCar();
        ShowSummedPrice();
        ShowMaxTransaction();
    }
    

    private void ShowExpCar(){
        
        expCar = db.getMaxPriceCar();
        String value;
        expCarPrice = expCar.get(4);
        expCarData = "";
        
        for(int i = 0; i<expCar.size();i++){
            if(i == 1 || i == 2 || i == 5){
                value = expCar.get(i);
                expCarData = expCarData + " " + value;
            }
                
        }
        
        EXP_TEXTFIELD.setText(expCarData);
        EXP_PRICE_TEXTFIELD.setText(expCarPrice);
    }
    
    private void ShowCheapCar(){
        
        cheapCar = db.getMinPriceCar();
        String value;
        cheapCarPrice = cheapCar.get(4);
        cheapCarData = "";
        
        for(int i = 0; i<cheapCar.size();i++){
            if(i == 1 || i == 2 || i == 5){
                value = cheapCar.get(i);
                cheapCarData = cheapCarData + " " + value;
            }
                
        }
        
        CHEAP_TEXTFIELD.setText(cheapCarData);
        CHEAP_PRICE_TEXTFIELD.setText(cheapCarPrice);
    }
    
    private void ShowSummedPrice(){
        String value = "";
        summedPrice = db.getSummedPrice();
        value = Integer.toString(summedPrice);
        SUMMED_PRICE_TEXTFIELD.setText(value);
    }
    
    private void ShowMaxTransaction(){
        String value = "";
        maxTransactionValue = db.getMaxTransaction();
        value = Integer.toString(maxTransactionValue);
        MAX_TRANSACTION_TEXTFIELD.setText(value);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        EXP_TEXTFIELD = new javax.swing.JTextField();
        EXP_PRICE_TEXTFIELD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CHEAP_TEXTFIELD = new javax.swing.JTextField();
        CHEAP_PRICE_TEXTFIELD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        SUMMED_PRICE_TEXTFIELD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        MAX_TRANSACTION_TEXTFIELD = new javax.swing.JTextField();

        setBackground(new java.awt.Color(240, 153, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("Najdroższy samochód:");

        EXP_TEXTFIELD.setEditable(false);
        EXP_TEXTFIELD.setText("Auto");
        EXP_TEXTFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXP_TEXTFIELDActionPerformed(evt);
            }
        });

        EXP_PRICE_TEXTFIELD.setEditable(false);
        EXP_PRICE_TEXTFIELD.setText("Wartość");

        jLabel2.setText("Najtańszy samochód:");

        CHEAP_TEXTFIELD.setEditable(false);
        CHEAP_TEXTFIELD.setText("Auto");
        CHEAP_TEXTFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHEAP_TEXTFIELDActionPerformed(evt);
            }
        });

        CHEAP_PRICE_TEXTFIELD.setEditable(false);
        CHEAP_PRICE_TEXTFIELD.setText("Wartość");

        jLabel3.setText("Łączna wartość samochodów:");

        SUMMED_PRICE_TEXTFIELD.setEditable(false);
        SUMMED_PRICE_TEXTFIELD.setText("Wartość");

        jLabel4.setText("Wartość największej transakcji:");

        MAX_TRANSACTION_TEXTFIELD.setEditable(false);
        MAX_TRANSACTION_TEXTFIELD.setText("Wartość");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EXP_TEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EXP_PRICE_TEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CHEAP_TEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CHEAP_PRICE_TEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SUMMED_PRICE_TEXTFIELD)
                            .addComponent(MAX_TRANSACTION_TEXTFIELD))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EXP_TEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EXP_PRICE_TEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CHEAP_TEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CHEAP_PRICE_TEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(SUMMED_PRICE_TEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(MAX_TRANSACTION_TEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EXP_TEXTFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXP_TEXTFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EXP_TEXTFIELDActionPerformed

    private void CHEAP_TEXTFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHEAP_TEXTFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CHEAP_TEXTFIELDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CHEAP_PRICE_TEXTFIELD;
    private javax.swing.JTextField CHEAP_TEXTFIELD;
    private javax.swing.JTextField EXP_PRICE_TEXTFIELD;
    private javax.swing.JTextField EXP_TEXTFIELD;
    private javax.swing.JTextField MAX_TRANSACTION_TEXTFIELD;
    private javax.swing.JTextField SUMMED_PRICE_TEXTFIELD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
